# Generated by Django 5.1.4 on 2024-12-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
